<?php
/**
 * 菜单配置文件
 */

return array (
  0 => 
  array (
    'type' => 'file',
    'name' => 'templates',
    'title' => '模板管理',
    'icon' => 'fa fa-window-restore',
    'url' => '',
    'condition' => '',
    'remark' => '',
    'ismenu' => 1,
    'menutype' => NULL,
    'extend' => '',
    'weigh' => 0,
    'sublist' => 
    array (
      0 => 
      array (
        'type' => 'file',
        'name' => 'templates/templates',
        'title' => '模板列表',
        'icon' => 'fa fa-window-restore',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/index',
            'title' => '模板列表',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/add',
            'title' => '创建模板',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/edit',
            'title' => '使用模板',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/reset',
            'title' => '重置模板',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/del',
            'title' => '删除模板',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/package',
            'title' => '模板打包',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/local',
            'title' => '上传安装模板',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/config',
            'title' => '模板配置',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          8 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/addconfig',
            'title' => '添加模板配置',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          9 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/langs',
            'title' => '多语言管理',
            'icon' => 'fa fa-language',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          10 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/langsadd',
            'title' => '多语言添加',
            'icon' => 'fa fa-plus',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          11 => 
          array (
            'type' => 'file',
            'name' => 'templates/templates/langsedit',
            'title' => '多语言修改',
            'icon' => 'fa fa-plus',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
    ),
  ),
);